package it.polimi.ingsw.Client.LightView.LightUtilities;

/**
 * Contains a simple String. It is used as the return value of the factory methods of the Information Generator interface,
 * and contains client generated error and information messages.
 */
public class InternalMessage
{
    private String infoMessage;


    /** Class constructor: instantiates the infoMessage
     * @param message the string generated by the factory method "InformationCreator"
     */
    public InternalMessage(String message)
    {
        this.infoMessage = message;
    }

    public String getInfoMessage(){return  infoMessage;}
}
