package it.polimi.ingsw.Client.LightView.LightUtilities;

public class InternalMessage
{
    private String infoMessage;


    /** Class constructor: instantiates the infoMessage, which can be a client generated hint or error message
     * @param message the string generated by the factory method "InfoGenerator"
     */
    public InternalMessage(String message)
    {
        this.infoMessage = message;
    }

    public String getInfoMessage(){return  infoMessage;}
}
