package it.polimi.ingsw.Client.GUI.Controllers;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.control.Button;
import javafx.stage.Stage;

public class IntroController extends Controller{
    @FXML public Button Start;
    @FXML public Button Close;
    @FXML public Button Story;

    /**This method handle the press of the exit button used to close the game, closing the game window
     * @param actionEvent is the event that is generated by the pressing of the exit button
     */
    public void oncClickExitButton(ActionEvent actionEvent)
    {
        Stage stage=(Stage) ((Node)actionEvent.getSource()).getScene().getWindow();
        stage.close();
    }

    /**This method is called when the Start button is pressed and use the loadNewScreen method, inherited from the
     * abstract class controller, to replace the current scene with the Login scene (specified in the variable called path).
     * Then it also calls the setGuiMainStarter method, inherited from the Controller class, to preserve the reference
     * to the main class guiMainStarter and the initialize function that do the setup of the associate LoginController.
     */
    public void onClickStart()  {
        String path= "/Client/GUI/Controllers/Login.fxml";
        FXMLLoader loader=loadNewScreen(path);
        LoginController controller = loader.getController();
        controller.setGuiMainStarter(guiMainStarter);
        controller.initialize();
    }

    /**This method is called when the Story button is pressed and use the loadNewScreen method, inherited from
     * the abstract class Controller, to replace the current scene with the Description scene The location of the
     * new screen it's stored in the variable called path.
     * Then it also calls the setGuiMainStarter method, inherited from the Controller class, to preserve the reference
     * to the class guiMainStarter.
     */
    public void onClickStory() {
        String path= "/Client/GUI/Controllers/Description.fxml";
        FXMLLoader loader=loadNewScreen(path);
        DescriptionController controller = loader.getController();
        controller.setGuiMainStarter(this.guiMainStarter);
    }
}
